spring:
    datasource:
        url: jdbc:h2:mem:quasardb
        username: maelstrom
        password: maelstrom
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console.enabled: true